package modelo;
// Generated 10-mar-2021 16:13:18 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Empleados generated by hbm2java
 */
public class Empleados  implements java.io.Serializable {


     private Integer idEmpleado;
     private String nombre;
     private String apellido;
     private String dni;
     private Date fechaNacimiento;
     private String telefono;
     private String direccion;
     private Integer codPostal;
     private String puesto;
     private String departamento;
     private Float salario;
     private Boolean sexo;
     private byte[] imagen;
     private String nombreUsuario;
     private String contrasenha;
     private String rol;
     private Date fechaAlta;
     private Set ventases = new HashSet(0);
     private Set comprases = new HashSet(0);

    public Empleados() {
    }

    public Empleados(String nombre, String apellido, String dni, Date fechaNacimiento, String telefono, String direccion, Integer codPostal, String puesto, String departamento, Float salario, Boolean sexo, byte[] imagen, String nombreUsuario, String contrasenha, String rol, Date fechaAlta, Set ventases, Set comprases) {
       this.nombre = nombre;
       this.apellido = apellido;
       this.dni = dni;
       this.fechaNacimiento = fechaNacimiento;
       this.telefono = telefono;
       this.direccion = direccion;
       this.codPostal = codPostal;
       this.puesto = puesto;
       this.departamento = departamento;
       this.salario = salario;
       this.sexo = sexo;
       this.imagen = imagen;
       this.nombreUsuario = nombreUsuario;
       this.contrasenha = contrasenha;
       this.rol = rol;
       this.fechaAlta = fechaAlta;
       this.ventases = ventases;
       this.comprases = comprases;
    }
   
    public Integer getIdEmpleado() {
        return this.idEmpleado;
    }
    
    public void setIdEmpleado(Integer idEmpleado) {
        this.idEmpleado = idEmpleado;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    public String getDni() {
        return this.dni;
    }
    
    public void setDni(String dni) {
        this.dni = dni;
    }
    public Date getFechaNacimiento() {
        return this.fechaNacimiento;
    }
    
    public void setFechaNacimiento(Date fechaNacimiento) {
        this.fechaNacimiento = fechaNacimiento;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public Integer getCodPostal() {
        return this.codPostal;
    }
    
    public void setCodPostal(Integer codPostal) {
        this.codPostal = codPostal;
    }
    public String getPuesto() {
        return this.puesto;
    }
    
    public void setPuesto(String puesto) {
        this.puesto = puesto;
    }
    public String getDepartamento() {
        return this.departamento;
    }
    
    public void setDepartamento(String departamento) {
        this.departamento = departamento;
    }
    public Float getSalario() {
        return this.salario;
    }
    
    public void setSalario(Float salario) {
        this.salario = salario;
    }
    public Boolean getSexo() {
        return this.sexo;
    }
    
    public void setSexo(Boolean sexo) {
        this.sexo = sexo;
    }
    public byte[] getImagen() {
        return this.imagen;
    }
    
    public void setImagen(byte[] imagen) {
        this.imagen = imagen;
    }
    public String getNombreUsuario() {
        return this.nombreUsuario;
    }
    
    public void setNombreUsuario(String nombreUsuario) {
        this.nombreUsuario = nombreUsuario;
    }
    public String getContrasenha() {
        return this.contrasenha;
    }
    
    public void setContrasenha(String contrasenha) {
        this.contrasenha = contrasenha;
    }
    public String getRol() {
        return this.rol;
    }
    
    public void setRol(String rol) {
        this.rol = rol;
    }
    public Date getFechaAlta() {
        return this.fechaAlta;
    }
    
    public void setFechaAlta(Date fechaAlta) {
        this.fechaAlta = fechaAlta;
    }
    public Set getVentases() {
        return this.ventases;
    }
    
    public void setVentases(Set ventases) {
        this.ventases = ventases;
    }
    public Set getComprases() {
        return this.comprases;
    }
    
    public void setComprases(Set comprases) {
        this.comprases = comprases;
    }




}


