package modelo;
// Generated 10-mar-2021 16:13:18 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Productos generated by hbm2java
 */
public class Productos  implements java.io.Serializable {


     private Integer idProducto;
     private Clientes clientes;
     private Proveedores proveedores;
     private String nombre;
     private String descripcion;
     private Integer unidades;
     private Float precio;
     private String categoria;
     private byte[] imagen;
     private Set comprases = new HashSet(0);
     private Set ventases = new HashSet(0);

    public Productos() {
    }

    public Productos(Clientes clientes, Proveedores proveedores, String nombre, String descripcion, Integer unidades, Float precio, String categoria, byte[] imagen, Set comprases, Set ventases) {
       this.clientes = clientes;
       this.proveedores = proveedores;
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.unidades = unidades;
       this.precio = precio;
       this.categoria = categoria;
       this.imagen = imagen;
       this.comprases = comprases;
       this.ventases = ventases;
    }
   
    public Integer getIdProducto() {
        return this.idProducto;
    }
    
    public void setIdProducto(Integer idProducto) {
        this.idProducto = idProducto;
    }
    public Clientes getClientes() {
        return this.clientes;
    }
    
    public void setClientes(Clientes clientes) {
        this.clientes = clientes;
    }
    public Proveedores getProveedores() {
        return this.proveedores;
    }
    
    public void setProveedores(Proveedores proveedores) {
        this.proveedores = proveedores;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Integer getUnidades() {
        return this.unidades;
    }
    
    public void setUnidades(Integer unidades) {
        this.unidades = unidades;
    }
    public Float getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(Float precio) {
        this.precio = precio;
    }
    public String getCategoria() {
        return this.categoria;
    }
    
    public void setCategoria(String categoria) {
        this.categoria = categoria;
    }
    public byte[] getImagen() {
        return this.imagen;
    }
    
    public void setImagen(byte[] imagen) {
        this.imagen = imagen;
    }
    public Set getComprases() {
        return this.comprases;
    }
    
    public void setComprases(Set comprases) {
        this.comprases = comprases;
    }
    public Set getVentases() {
        return this.ventases;
    }
    
    public void setVentases(Set ventases) {
        this.ventases = ventases;
    }




}


